// Placeholder for interacting with the Wasm module
// In a real build, sphereslam_web.js would be generated by Emscripten
// and we would import it.

// Assuming emcc output is named sphereslam_web.js
import createSphereSLAMModule from '../web_lib/build/sphereslam_web.js';

const statusDiv = document.getElementById('status');
const startBtn = document.getElementById('start-btn');

let slamSystem = null;

async function init() {
    try {
        statusDiv.innerText = "Status: Loading Wasm...";

        // Initialize the module
        const Module = await createSphereSLAMModule();

        statusDiv.innerText = "Status: Wasm Loaded";

        // Create SLAM System
        // Paths are virtual paths in the Emscripten FS (need preloading)
        slamSystem = new Module.System("ORBvoc.txt", "Settings.yaml");

        startBtn.disabled = false;
        statusDiv.innerText = "Status: Ready";

    } catch (e) {
        console.error("Failed to load Wasm", e);
        statusDiv.innerText = "Status: Error Loading Wasm";
    }
}

startBtn.addEventListener('click', async () => {
    if (!slamSystem) return;
    statusDiv.innerText = "Status: Starting Camera...";

    try {
        const stream = await navigator.mediaDevices.getUserMedia({ video: true });
        const video = document.createElement('video');
        video.srcObject = stream;
        video.play();

        const canvas = document.getElementById('camera-feed');
        const ctx = canvas.getContext('2d');

        // Resize canvas to match video
        video.onloadedmetadata = () => {
            canvas.width = video.videoWidth;
            canvas.height = video.videoHeight;
            loop();
        };

        function loop() {
            if (!slamSystem) return;

            ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
            const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);

            // Pass data to SLAM (Conceptual)
            // slamSystem.processFrame(imageData.data, canvas.width, canvas.height, performance.now());

            // Update stats
            const stats = slamSystem.getMapStats();
            const state = slamSystem.getTrackingState();
            statusDiv.innerText = `Status: Tracking (${state}) - ${stats}`;

            requestAnimationFrame(loop);
        }
    } catch (err) {
        console.error(err);
        statusDiv.innerText = "Status: Camera Error";
    }
});

// init();
console.log("Web App Script Loaded");
